### ISSUE TITLE
"Join by Invitation only" should check several criteria

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#120]
"Join by Invitation only" should check several criteria:
1) the invitee's email
2) the fact of invitation from the invitor of the invitee's email

**Comment by kisonik** [comment]
It would also be great if a connection could be established between the inviter and the invitee.

**Comment by AlexTr** [comment]
@kisonik do you mean checking in the invitation form ?

**Comment by AlexTr** [comment]
we can't check the fact of invitation, since this data isn't stored anywhere, so **we can check only email**.
