### ISSUE TITLE
MAILER SMTP DON'T WORKING

### ISSUE THREAD

**Issue by francois007** [boonex/dolphin.pro#126]
"EMAIL SEND FAILED"
SMTP Mailer 1.2.1 not send email.
I have investigated in log server, but I find no trace of any errors.
A disaster Dolphin 7.2.1

**Comment by AlexTr** [comment]
I've just checked SMTP Mailer in Dolphin 7.2.1 it is working. Actually we have no changes in it so it should work as before. I would suggest to recheck you SMTP Mailer settings. 

If you still have problem please post in forums:
https://www.boonex.com/forums/
