### ISSUE TITLE
Timeline: video embed isn't shown on homepage timeline

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#128]
To reproduce the problem disable all uploaders except "Embed", so it will be shown when you select video in post to timeline, then upload video embed, as the result video embed isn't shown in homepage timeline, but only in profile timeline.

https://www.boonex.com/forums/topic/embed-to-own-timeline-7-2-1.htm

**Comment by launch3** [comment]
I embedded as text both a video and photo to the timeline. I also posted a link url to a news story. All 3 display on my profile timeline, but only the video displays on the home page timeline. The photo and link do not appear on the home page timeline.
