### ISSUE TITLE
BitPay issue: missing constant BX_DOL_URL_ROOT_SSL

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#137]
BitPay requires that the Notification URL be SSL-based
The code requires the constant BX_DOL_URL_ROOT_SSL to be initialized while it is not.

**Comment by AlexTr** [comment]
I think we don't need BX_DOL_URL_ROOT_SSL, it's a problem to enable HTTPS on some one page, it's better and easier to enable HTTPS on the whole site.
