### ISSUE TITLE
Payment before join: no way to select payment provider

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#139]
Related issue - #143

It looks like join form payment is working with PayPal only. If "Payment" module is used and several payment providers are activated, or other than PayPal providers is activated - you can't on on join form: 
![screen shot 2015-10-27 at 2 15 02 pm](https://cloud.githubusercontent.com/assets/3324866/10748525/2c6a2bde-7cb5-11e5-8fbb-db76056a352d.png)

Also there is problem with padding/margin on paid join form - no space below the line:
![screen shot 2015-10-27 at 2 16 22 pm](https://cloud.githubusercontent.com/assets/3324866/10748538/6a85bbe0-7cb5-11e5-86de-b33deb7caff8.png)

**Comment by AlexTr** [comment]
@AntonLV  please post notification here as soon as this problem is fixed - https://app.intercom.io/a/apps/ss0u2e8q/inbox/dev@boonex.com/conversations/1351876397

**Comment by AntonLV** [comment]
1. Right now PayPal and 2Checkout from Payment module are available for "pay before join". Take a look at 'for_visitor' flag in 'bx_pmt_providers' DB table. BitPay is not available for "pay before join" because of delayed payments processing.

**Comment by AntonLV** [comment]
2. The issue with padding/margin was fixed.

**Comment by AlexTr** [comment]
Ok, thank you for letting know. Also there is a minor problem: when no one payment method is available on join form, there is a caption "SELECT PAYMENT METHOD" with no options - I think it should be some error message there instead - for example "No payment methods available"

**Comment by AntonLV** [comment]
Minor issue with "SELECT PAYMENT METHOD" was fixed.
