### ISSUE TITLE
Moxie Manager photo album upload??

### ISSUE THREAD

**Issue by robbie778** [boonex/dolphin.pro#145]
This is not a bug but hopefully an enhancement, still when you upload images via certain mobile devices the images are coming up with the error (invalid file format) in 7.2.0, I am wondering if it is possible to implement Moxie Manager for the upload of photo's and avatar?

Moxie manager has so far worked with all mobile devices ive tested when uploading images.

**Comment by AlexTr** [comment]
The problem has been fixed in #34
