### ISSUE TITLE
Mobile apps can't connect to SSL-enabled sites (https)

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#146]
Mobile apps can't connect to SSL-enabled sites (https)

**Comment by AlexTr** [comment]
No problem noticed in iOS app, however it was a problem when iOS app can't connect to NOT SSL enabled site - it has been fixed:
https://github.com/boonex/dolphin-ios/commit/a5146ba7a73b6b8832f85188a7e00bd7eda15dec
