### ISSUE TITLE
Add video support in MoxieManager

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#159]
The video support in MoxieManager is not fully integrated.
We need to add additional allowed extensions in the file: plugins\moxiemanager\config.php
The possible extensions can be obtained from here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by AlexTr** [comment]
Add **.webm** and **.mp4** to the allowed files in config.php in moxiemanager.

**Comment by AntonLV** [comment]
Done.
