### ISSUE TITLE
Double notifications in spy module

### ISSUE THREAD

**Issue by apachler** [boonex/dolphin.pro#164]
I always get double notifications for accepted friends requests in spy module.
I cant find anything with alerts or alert handlers in the database that is not correct.
It seems that the double notifications are not triggered everytime.

Please see the attached screenshots.

![double_notification](https://cloud.githubusercontent.com/assets/3908272/10936333/6700a24a-82ec-11e5-8d13-d2b7465463e1.png)
![sys_alerts](https://cloud.githubusercontent.com/assets/3908272/10936331/66f657cc-82ec-11e5-956c-9787c03702d0.png)
![sys_alerts_handlers](https://cloud.githubusercontent.com/assets/3908272/10936398/c49c5bf6-82ec-11e5-99a0-870b21f25b2a.png)
![bx_spy_data](https://cloud.githubusercontent.com/assets/3908272/10936329/66d6c40c-82ec-11e5-9be3-70c6fe266c49.png)

**Comment by AlexTr** [comment]
There are two blocks with friend requests nn friends confirm page, it maybe that user confirm friend request twice in both blocks. So the event shouldn't be triggered when friendship is confirmed when members are already friends and it would be great to reload another block via AJAX upon friend request confirmation.

**Comment by AlexTr** [comment]
https://www.boonex.com/forums/topic/timeline-posting-twice-in-7-2-1-.htm

**Comment by AntonLV** [comment]
The repeated alert firing was fixed. 
P.S. Communicator uses unified method to process actions, which was written to update the content of the block from which the action was called. So, we would need to add custom check especially for Friend Requests which is not so good, I think.
