### ISSUE TITLE
Privacy: site-wide default privacy values

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#165]
Now it is editable via DB only. Especially the problem has place when Public privacy group is disabled and some other group need to be set as default.

https://www.boonex.com/forums/topic/Setting-default-content-albums-privacy-.htm

**Comment by moonsoon2u** [comment]
There should be option in admin control panel for separate privacy setting for default albums( wall,cover, profile) besides the default privacy group.
