### ISSUE TITLE
function to get info if site is on SSL

### ISSUE THREAD

**Issue by apachler** [boonex/dolphin.pro#173]
Would be nice to have a function to get the info if site is on SSL.

Or maybe something where we can get the scheme, like that:
function getUrlScheme() {
    return (!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] != "on") ? 'http://' : 'https://';
}

With that function we can set the scheme for external sources like gMaps etc ...

**Comment by AlexTr** [comment]
bx_proto function was added: cb58da7749b833d34bd079affd16534bacb2ef75
