### ISSUE TITLE
Timeline: add like to timeline

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#179]
I think that regular voting should be added to the timeline posts, at the same time or later we need to remake voting to look it like "Like" instead of "Stars"

--

add "like" button to the "timeline" (next to "delete" and "comment" button"). Then the user can click "like" to the blog, group, post, etc. in the "timeline" and this action can also be seen by the friends in their timeline.

**Comment by jdelasko** [comment]
Can you please take an opinion poll before you do this?  I don't think this would be an improvement.  You don't gain anything by doing this. In fact, you lose something.

**Comment by launch3** [comment]
I like it (excuse the pun). Testing it on 4 sites.
