### ISSUE TITLE
Predefined values builder: countries list isn't saving

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#180]
Most probably because of the following error:
```html
<b>Warning</b>:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in <b>Unknown</b> on line <b>0</b><br />
```

**Comment by toxalot** [comment]
So does that mean the extra fields are never used? There is a comment in the database structure that says, "Some extra values. For example image link for sex". However, with this commit you are not saving those fields anymore.

I've dug into the code a bit and it does appear that the sex icons are hard-coded. I was planning on modifying that. I need to make several custom genders with custom icons. Using the extra field in predefined values would have been ideal for this.

**Comment by AlexTr** [comment]
Return 'Extra' field back - #270

**Comment by pletchman** [comment]
I am having an issue with more entries not saving. I created a new list which I believe has around 200 or so but can't enter last of them because they don't save when clicking "save". Overall that sys_pre_value has a total of 675 entries. If there (which of course there shouldn't be) a max record

**Comment by AlexTr** [comment]
@pletchman There is a limit of number of fields for POST in PHP. By default it's 1000. One row in predefined fields builder consists of 4 fields, as the result the default limit for number of fields in pre-lists is 1000/4 = **250 values**.
You can change it by editing `max_input_vars` PHP setting.

**Comment by pletchman** [comment]
@AlexTr thanks. I did some digging and figured that out as well. Already upped ours to 10,000 so hopefully no issues
