### ISSUE TITLE
Facebook: new API 2.5 adds postfix after the username

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#183]
The new API 2.5 adds the _fb postfix after the username which prevents members from logging into the same account on your website they used to log into.

**Comment by moonsoon2u** [comment]
Facebook connect is registering members without the email address in the database. It is causing member without email to login in to random members account.

**Comment by AlexTr** [comment]
@kisonik please clarify regarding _fb suffix ? it is added only if the same username already exist in the db

**Comment by AlexTr** [comment]
@moonsoon2u thank you we'll check this out.

**Comment by kisonik** [comment]
@AlexTr , yes, it seems like it happens only when such username already exists
@moonsoon2u , I have not noticed such problem in 7.2.1 with Facebook API 2.4 or 2.5

**Comment by AlexTr** [comment]
@kisonik  that's normal situation in the case when usernames are the same but emails are different, but if emails match - user is logged in into correct account

**Comment by AntonLV** [comment]
@moonsoon2u, I, too, was unable to reproduce the problem.

**Comment by moonsoon2u** [comment]
![no email account for users problem](https://cloud.githubusercontent.com/assets/14203020/11765644/61a3e546-a182-11e5-9595-749574c82990.jpg)
This happened again recently. A user without email address. On my website the email verification is off.
