### ISSUE TITLE
Pages Builder: <script> blocks don't preserve after being saved

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#190]
Pages Builder: <script> blocks don't preserve after being saved.
That is, you can't edit them because they just disappear from the editor.

**Comment by kisonik** [comment]
After being saved, the script tags disappear if you want to edit the containing HTML blocks.

**Comment by AlexTr** [comment]
The problem is in TinyMCE, it strips any JS code, even if you disable TinyMCE, it is enabling again upon opening the block and strips the code again.
**I would suggest to save toggle state for tinymce are in a cookie, so if user disables tinymce it will saved.**

**Comment by AntonLV** [comment]
Alex, I have a question about cookie. Should it be installed especially for this current block or simply for all TinyMCE for given user. I think it would be better to set for the block only.

**Comment by AlexTr** [comment]
There is already "toggle htmleditor" functionality - but the sate isn't saved, so make an enhancement in it, as I remember this flag is for all forms, but this flag is used only in html block form only, I suspect that it maybe useful somewhere else.

**Comment by AlexTr** [comment]
I think it would be better to have two different blocks HTML Block and Text Blocks

**Comment by jdelasko** [comment]
Separate HTML and Text blocks are the best idea I've heard yet.  HTML blocks should be just that... a block where you use HTML code, and leave TinyMCE out of the picture.   Use TinyMCE for the text block.  TinyMCE in the  HTML block has been nothing but an annoyance for most people. While TinyMCE in  the HTML block may help beginners, it does so at the expense of more experienced users.

We need 4 block types:

RSS
TEXT
HTML
PHP

**Comment by AlexTr** [comment]
PHP block is hidden by default, but you can enable it by opening the following URL:
```
http://example.com/path-to-dolphin/administration/pageBuilder.php?action_sys=addCodeBlock
```
Or remove it:
```
http://example.com/path-to-dolphin/administration/pageBuilder.php?action_sys=removeCodeBlock
```
