### ISSUE TITLE
iPhone Users Posting Comments To Timeline Logs User Out

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#195]
Have an iPhone bug reported by a member.

When a member tries to post a comment to a timeline post on the homepage using their iPhone, it logs them out and closes the page.

I have an Android and did not have a problem posting comments. Seems limited to iPhone.

![timeline-iphone-comment-logout](https://cloud.githubusercontent.com/assets/13964338/11305403/84351edc-8f7a-11e5-85de-a1a03b3d5190.jpg)

**Comment by AlexTr** [comment]
It should be fixed in 7.3.0
