### ISSUE TITLE
Timeline Cuts Off Some Images

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#208]
I'm posting images from imgur.com right into the timeline (where it auto-embeds upon posting).
Why do the tops & bottoms of some images get cut off at 480w x 270h, while others do not?
How do I change these settings?
The seemingly randomness of it is making me crazy.

![embed-timeline-cutoff-top-bottom](https://cloud.githubusercontent.com/assets/13964338/11608627/bcf4c4fc-9b3c-11e5-8eec-c16dfd5c0185.png)

**Comment by AlexTr** [comment]
https://www.boonex.com/forums/topic/Why-Does-Timeline-Cut-Off-Images-.htm

**Comment by launch3** [comment]
When posting images to the timeline (embedded or uploaded), timeline either cuts off the top & bottom (attached image from my initial post) or cuts off the left & right of a thumbnail (attached below).
  
I can make the images larger & smaller (via wall module view.css), but I cannot figure out how to stop it from cutting off images. How can I get Dolphin to post a complete image at a reduced size, one that's NOT missing a top, bottom, left or right side?

![timeline-cuts-off-left-right-too](https://cloud.githubusercontent.com/assets/13964338/12079443/2bb1de12-b207-11e5-8c23-e3c4b7e0cba0.png)

**Comment by launch3** [comment]
So there's no title for an image (video & sound too) in the timeline (https://github.com/boonex/dolphin.pro/issues/205), plus it also cuts off tops, bottoms, lefts and rights.

Visitors, members and myself have no idea what they are looking at.

Please correct this. It is sooo frustrating.

**Comment by AlexTr** [comment]
Images are cut-off during resizing you can change this behaviour by changing the the following lines in modules/boonex/photos/classes/BxPhotosConfig.php file:
```php
...
'browse' => array('postfix' => '_t.jpg', 'size_def' => 240, 'square' => false),
'browse2x' => array('postfix' => '_t_2x.jpg', 'size_def' => 480, 'square' => false),
...
```
