### ISSUE TITLE
Timeline: Boxes Not Aligned For 3rd Party Mods

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#209]
I'm posting and posting to the timeline. Everything is aligned (thumbnail & post) when I use text, link, video, audio, sound.
However, when a post using a 3rd party module appears in the timeline, the thumbnail & post are misaligned (image below). Happens with Ultimate Articles, PKForum & all the mods I have.
Not sure how to fix.

![timeline-boxes-not-aligned](https://cloud.githubusercontent.com/assets/13964338/11608633/dfdceabc-9b3c-11e5-8152-efcac020eaec.png)

![timeline-boxes-not-aligned2](https://cloud.githubusercontent.com/assets/13964338/11608634/e396d348-9b3c-11e5-8697-a79bd82df475.png)

**Comment by AlexTr** [comment]
https://www.boonex.com/forums/topic/Timeline-Boxes-Not-Aligned-For-3rd-Party-Mods.htm

**Comment by launch3** [comment]
![timeline-modzzz](https://cloud.githubusercontent.com/assets/13964338/11768236/5346b7aa-a194-11e5-9b92-88511195816d.png)

   
![timeline-pkforum](https://cloud.githubusercontent.com/assets/13964338/11768239/5b5896d4-a194-11e5-98d8-c21230554b16.png)
