### ISSUE TITLE
Shoutbox Bug...  see the screenshot!!

### ISSUE THREAD

**Issue by vazahat** [boonex/dolphin.pro#221]
![untitled](https://cloud.githubusercontent.com/assets/7565660/11912035/21dca1ae-a651-11e5-872b-f6e5f26debd6.jpg)

when typing symbols more then 3 to 4... the shoutbox windows is showing the symbols  as well as showing their perspective name too.. isn't this wierd... for example i had typed '??????' and shoutbox is showing '???&que­st;??­ ' why its showing '&quest,' 
i have tested it with dolphin sample site...

**Comment by AlexTr** [comment]
#144 
The fix - 150cd0ea480dc0bf5140e196da0c246c6376188e
