### ISSUE TITLE
Timeline: allow to enable/disable particular uploaders in Timeline

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#255]
https://www.boonex.com/forums/topic/Removing-Audio-from-Post-To-Timeline-.htm

**Comment by toxalot** [comment]
It's already possible to disable uploaders site-wide. I'm not sure someone really needs different uploaders for different areas of the site. Unless disabling all uploaders for timeline will disable that option altogether for the timeline only. For example, I want to allow photos on the site, but I don't want them uploaded directly to timeline. I only want people to be able to add text comments directly to timeline.
