### ISSUE TITLE
Ability to Rotate Photos Without Cropping

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#258]
I would like users to be able to rotate photos 90 degrees without being forced to crop it as well.

**Comment by AlexTr** [comment]
Photos are rotated automatically based on Exif information fro the photo.

**Comment by toxalot** [comment]
Well, it doesn't seem to work all the time. Are there circumstances where Exif orientation info is missing?

**Comment by AlexTr** [comment]
Yes, the only reason when it is not auto-rotating is the case of missing Exif data or it is incorrect.

**Comment by toxalot** [comment]
So it would be nice to have the option to rotate rectangular photos that didn't get auto-rotated without having to crop them square.
