### ISSUE TITLE
Extended Member List and Profile Search Don't Respect Privacy

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#259]
The Description block is still searchable and still displays in extended view even if the member has stricter privacy on the whole profile or that individual block.

**Comment by toxalot** [comment]
@AlexTr There is still a privacy issue here. The privacy of the special Description block is not checked. And the privacy of the block that includes the DescriptionMe field is not checked either.

**Comment by AlexTr** [comment]
@toxalot please could you be more descriptive ? For me when profile is private, then only "Information availability is limited by member privacy." message is displayed.

**Comment by toxalot** [comment]
If the profile itself is viewable, but the block is not. For example if I set my profile privacy to Members, but set the privacy on the block itself to Friends. Only friends can see the block on my page, but members can see the first 130 characters in extended mode.

**Comment by camperjz** [comment]
Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>



On Mon, Feb 22, 2016 at 4:09 PM -0800, "Alex Trofimov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #259<https://github.com/boonex/dolphin.pro/issues/259>.

-
