### ISSUE TITLE
Calendar: month names are not translated

### ISSUE THREAD

**Issue by fczhG1HE** [boonex/dolphin.pro#260]
https://www.boonex.com/forums/topic/Calendar-language-problem.htm

BxDolCalendar.php:185
- return $this->sMonthName . ', ' . $this->iYear;
+ return _t('_'.$this->sMonthName) . ', ' . $this->iYear;

**Comment by AlexTr** [comment]
Month name should be translated, because it is generated using `strftime` php function with the current locale

**Comment by fczhG1HE** [comment]
That doesn't work on demo.boonex.com (set lang to russian).
Server locale and chosen language in dolphin can differ.

**Comment by fczhG1HE** [comment]
other suggestion:

BxDolCalendar.php:59

- $this->sMonthName = strftime('%B', mktime(0, 0, 0, $this->iMonth+1, $iDay, $this->iYear));
+ $this->sMonthName = t($this->iMonth+1);

…and make new lang keys for months

**Comment by AlexTr** [comment]
We'll check what is the problem...
