### ISSUE TITLE
CSS z-index for sys-bm-switcher-language not high enough

### ISSUE THREAD

**Issue by fczhG1HE** [boonex/dolphin.pro#261]
sys-bm-switcher-language has z-index:

.bx-def-z-index-modal
z-index: 1000;

But if sys-loading is underneath it you can't click on language switcher.

div.sys-loading-smog
z-index:1101;

**Comment by AlexTr** [comment]
Thank you for the report, but It maybe a problem when loading indicator in the popup, then if we change z-index - loading indicator will not be shown in popup.
