### ISSUE TITLE
Browse Members Doesn't Drill Down Properly

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#263]
On the demo site, there is only one member that falls into the 36-38 age group. When you click that, the country section shows that there is one member in AU and one member is US. Of course, when you click the US link, it shows zero results.

**Comment by toxalot** [comment]
It gets even worse if you add a couple profile. I added a couple profile where the first person was a 20 year old female and the second person was a 50 year old male with country of AF.

When I first go to the All Members page, it shows 1 women, 7 men, 1 18-20, 1 48-50, and 1 AF. When I click AF, it says there is 1 women and 1 18-20. It should show that there is 1 men and 1 48-50 as well. Now I understand that country is a mutual field, but if sex and age are going to count separately (which I think they should) then they should show up.

Now if I go back to all members and then click 7 men, it only shows me 6 members. The couple profile is filtered out. Yet, the age section still shows that there is a person in the 48-50 age group. Of course, if I click on that, I get zero results.

I think mutual fields should be ignored for the browse section, and it should show stats for all members regardless of whether or not they share a profile.

**Comment by AntonLV** [comment]
> On the demo site, there is only one member that falls into the 36-38 age group. When you click that, the country section shows that there is one member in AU and one member is US. Of course, when you click the US link, it shows zero results.
I cannot reproduce the issue on demo.boonex.com site. There are two members in 36-38 age group (the same stats are provided in the age group's counter). One of them from AU and the second one from US. Both profiles are available.

**Comment by AntonLV** [comment]
> It gets even worse if you add a couple profile. I added a couple profile where the first person was a 20 year old female and the second person was a 50 year old male with country of AF.
...

This part of the issue was fixed.
