### ISSUE TITLE
Remove Top When Rating Disabled

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#269]
The option to display Top profiles in the members block should be removed when profile rating is disabled.

**Comment by AlexTr** [comment]
'Top' is sorting algorithm which can be used for some different criteria than rating.

**Comment by toxalot** [comment]
@AlexTr Could you please clarify? For photos, 'Top' does seem to affect sorting. However, 'Top' in the members block on the home page seems to be a filter. It links to index.php?MembersMode=top and on my site and the demo site, it shows an empty result.

**Comment by AlexTr** [comment]
It affects both filtering and sorting, but the main purpose is sorting.

**Comment by toxalot** [comment]
Maybe other 'Top' items are used for sorting, but this one is not. It's a filter that excludes anyone who hasn't been rated at least twice. It doesn't make sense to have a menu item for something that will always return empty results.

Even if you don't exclude anyone, sorting by rating has no meaning or value if no one is rated.

I've been digging in the code, these all return different results...

index.php?MembersMode=top
browse.php?sort=rate
search.php?show=top
viewFriends.php?iUser=1&sort=rate

The index one is a filter, but the search one is not, which is not intuitive. To me, 'show' implies filter rather than sort. And they all use a slightly different ORDER BY clause. 'Top' members should give consistent results regardless of which page it is accessed from.

I've made the code changes for myself and will send a pull request for your consideration.
