### ISSUE TITLE
Textarea Displays on Bottom of Pages Builder

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#276]
In the beta release, there is a textarea that always displays at the bottom of the Pages Builder.

**Comment by AlexTr** [comment]
Can't reproduce. 
Could you provide screenshot ?
What is the browser are you using ?

**Comment by toxalot** [comment]
To confirm, you are checking 7.3 BETA? I'm using Firefox.

![temp](https://cloud.githubusercontent.com/assets/3107215/12713995/73107158-c8a8-11e5-88a6-4feb27911ce4.png)

**Comment by AlexTr** [comment]
Still can't reproduce in Firefox, it maybe you have some old file cached, please try to clear cache in Dolphin and cache in the browser.

**Comment by toxalot** [comment]
Hmm... I reloaded after clearing Dolphin cache and browser cache, and it's still there. However, I am also unable to reproduce on another computer with exact same version of Firefox.
