### ISSUE TITLE
Next Link on Photo Albums Block on Profile Page Doesn't Work

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#280]
When you add the photo albums block to the profile page, the 'next' button just reloads the page. The pagination links work if the block is added to the profile photos page or the photos home page, but not when added to the profile main page.

The block is also not centered on the profile main page like it is on other pages.

**Comment by AlexTr** [comment]
How you've added photo albums block to homepage ? there is no such bock by default.

**Comment by toxalot** [comment]
Not homepage, Profile page. I have a fresh install with no modifications. It's inserted with the code on line 194 of /modules/boonex/photos/install/sql/install.sql

`('profile', '1140px', 'Photo Albums', '_[db_prefix]_albums', 0, 0, 'PHP', 'return BxDolService::call(''photos'', ''get_profile_albums_block'', array($this->oProfileGen->_iProfileID), ''Search'');', 1, 28.1, 'non,memb', 0),`

**Comment by AlexTr** [comment]
Thank you for pointing this out, for some reason for me this block isn't navigating to the next page at all!
