### ISSUE TITLE
Can't Navigate Between Photos in Photo Albums Block

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#281]
When the Photo Albums block first loads, you can hover over the cover and click the right arrow to view the next picture in the album. However, once you use the pagination links to view more albums, you can no longer navigate between photos within any of the albums.

**Comment by gorenc** [comment]
I had similar issues on D 7.2 until I discovered that there are actualy two diffrent photo blocks, one called Profile Photos (lng. key: "_bx_photos_photo_album_block") and the other one is named: Profile photo (lng. key:"_bx_photos_photo_block" ) If first of the above is used on Profile page everything is OK but not if second one is used on profile page as Photo block...

**Comment by gorenc** [comment]
And just to be aware of Enable cache for HTML files in Cache can result in url not found.....when clicking on thumbnail photo on profile page

**Comment by toxalot** [comment]
Yes, there are several different profile photo blocks... Profile Photo, Profile Photo**s**, and Profile Photo Switcher. However, this report is not about any of those. It's about the Photo Albums block wherever it appears.

I've also reported similar issues that may or may not be related. #279 is specifically about the Profile Photo block and #280 is about a specific issue when Photo Albums block is placed on profile page.

**Comment by gorenc** [comment]
OK, sorry for miss understanding
I think #279 is related to what I was trying to say.
Will check out Albums block....
