### ISSUE TITLE
r parameter with encoded value appears in many URLs

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#303]
getLinkAddByPrams() excludes `_r` by default. Shouldn't it exclude `r` by default?

**Comment by AlexTr** [comment]
Excluding _r by default is correct behavior

**Comment by toxalot** [comment]
@AlexTr Why is `r` included as a parameter when it is not used with permalinks and it's already part of base URI otherwise? What is the purpose of a link like the following...
`modules/?r=photos/albums/my/manage/&r=photos%2Falbums%2Fmy%2Fmanage%2F`

I see now there are a couple of instances in the code where `r` is part of the array passed to getLinkAddByPrams(), but most times nothing is passed to it. So the issue is with the fact that Photos (and other modules) are not specifically excluding it.

**Comment by AlexTr** [comment]
@toxalot it shouldn't be unset all the time, only in the specific situations, please describe the situation with double `r` parameter and we'll try to investigate it

**Comment by toxalot** [comment]
Ok, yes I see some places where it is needed. I've already fixed the spot where I noticed it as part of a branch I am working on. I will submit a pull request when I am done testing.

**Comment by AlexTr** [comment]
Thank you, but we will include it in next version only, since 7.3 is almost ready.

**Comment by toxalot** [comment]
Understood.

**Comment by toxalot** [comment]
I think this can be closed now.
