### ISSUE TITLE
"Undefined" shows on Photos Home

### ISSUE THREAD

**Issue by newton27** [boonex/dolphin.pro#31]
The word "undefined" shows up on the Photo home page
![undefined-on-photo-home-pag](https://cloud.githubusercontent.com/assets/4349640/9622931/bbaace0e-5107-11e5-801a-640f41afcff6.jpg)

Chrome Version 44.0.2403.157 m
http://www.boonex.com/forums/topic/Error-Photos-home-page-in-Chrome.htm

**Comment by AlexTr** [comment]
I think this is from photos cover plugin...

**Comment by newton27** [comment]
Yes, I believe so too.
