### ISSUE TITLE
The word "undifined" shows up on the Photo home page

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#32]
The word "undifined" shows up on the Photo home page, top right when first navigating to the page in Chrome browser.
This only happens on a new load, a refresh of the page does not show the error.
​http://www.boonex.com/forums/topic/Error-Photos-home-page-in-Chrome.htm

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin.pro/issues/31

**Comment by newton27** [comment]
Has this been fixed?
