### ISSUE TITLE
Option to Disable Likes for non-members in Outline & Timeline

### ISSUE THREAD

**Issue by moonsoon2u** [boonex/dolphin.pro#329]
There should be option to disable Likes for non-members. Both Like & Repost can be visible to non-members but if they click them instead of performing action there could be a popup mentioning "You must Join to Like or Repost" . This way owner of the content will know who Liked or Reposted their content and non-member will get the idea that the website have those functionalities and they have to join to perform them.

**Comment by AlexTr** [comment]
It's already possible via Admin panel > Membership Levels > Settings > click "Actions" for "Non-member" > then disable "Vote" action
