### ISSUE TITLE
Timeline Issues

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#335]
1) Comments are still disjointed in timeline. In #256, @AlexTr stated that the issues with comments should be already fixed. Here's a screenshot showing how the same photo is indicating a different comment count. The content of the comment indicates where it was posted from. Three comments appear on the photo itself. The other comment only shows up in timeline.

2) Note how the photo title is formatted differently. The CSS classes have a bunch of `__mod_prefix__` template variables that have not been replaced.

3) Note how the Like count disappears when comments are opened.

4) Note how '1 replies' appears twice.

5) Note how linking is inconsistent. In the photo notification caption, nickname is linked but the word 'photo' is not. In the comment notification caption, nickname is not linked, but the word 'photo' is. I don't see why there needs to be any links in the caption. The avatar, photo, and photo title are already links. But if the caption contains links, then both the nickname and the word 'photo' should be links.

![temp1](https://cloud.githubusercontent.com/assets/3107215/13202080/6af5e1c2-d863-11e5-9de4-c8370782daa6.png)

**Comment by toxalot** [comment]
6) The upload selector is on the right even though the Select Files button is on the left.

7) The upload selector appears even though only one uploader is enabled.

**Comment by toxalot** [comment]
8) If a user uploads a photo and does not click submit, the photo is still uploaded. However, no notification shows up in timeline.

**Comment by toxalot** [comment]
9) It's not obvious that the comment icon and the comment count are two different links. And for users who are not allowed to comment, they only see a comment count with no indication of what it's about.

Aside from being confusing, it's really hard to click on one or the other on mobile devices.

The comment icon and count should be one combined link. It should open both the comment box and existing comments block for users who are allowed to comment. For users that are not allowed to comment, it should just open the existing comments.

**Comment by toxalot** [comment]
10) In #75, text and links posted to profile timeline stopped displaying on home timeline. However, photos (and presumably other media) posted to profile timeline still display on home timeline. This inconsistency is confusing to users.

**Comment by toxalot** [comment]
11) 'Hide events from Timeline' appears to have duplicate settings for comments. And what is `_wall_alert_module_comment (add item)`?

![temp1](https://cloud.githubusercontent.com/assets/3107215/13203178/4d34269c-d888-11e5-9587-3dda1ef5a5c2.png)

**Comment by AlexTr** [comment]
8) is correct behaviour

**Comment by toxalot** [comment]
12) Multiple photos no longer group together. This wastes a lot of space. Titles should appear over the photo the same as they appear elsewhere. Photos should be grouped. And when photos are grouped,  comments/likes should be on the album and repost disabled.

**Comment by toxalot** [comment]
> 8) is correct behaviour

Is this a limitation or by design? Users are lazy and it sucks that there's no notification if they miss the last step.

**Comment by AlexTr** [comment]
> Is this a limitation or by design? Users are lazy and it sucks that there's no notification if they miss the last step.
Yes, `Alert` is called upon form submission, if we call `Alert` earlier then wall (and other modules) will pickup wrong info (before the form submission).

**Comment by AlexTr** [comment]
13) When inactive profile tries to post to timeline loading indicator never completes. Output:
```html
<script>parent.oWallPost._loading(null, false);
alert('Your membership level does not allow you to post here');</script>
```
JS error:
```
TypeError: parent.oWallPost._loading is not a function. (In 'parent.oWallPost._loading(null, false)', 'parent.oWallPost._loading' is undefined)
```

14) When Voting object is disabled, then "vote/like" action should be hidden in Timeline/Outline

**Comment by AlexTr** [comment]
10) It looks correct - item posted directly to profile Timeline isn't shown on homepage timeline, however items posted directly to Homepage timeline showed on both Profile and Homepage Timelines. Also photo posted in the Photo module displayed on both timelines too.

**Comment by toxalot** [comment]
10) Text/links posted directly to profile timeline aren't shown on homepage timeline, but photos posted directly to profile timeline DO show on homepage timeline.

**Comment by AlexTr** [comment]
10) I've just checked on https://demozzz.com/dolphin730b/ and can't reproduce the issue.

**Comment by toxalot** [comment]
10) Huh, I created an account and couldn't reproduce either. I thought it was maybe because I was posting as an admin on my site, but I can't reproduce at all now.

**Comment by toxalot** [comment]
15) Privacy of timeline Album is set to Public instead of default value set in admin.

**Comment by AlexTr** [comment]
15) It's better to keep Timeline Photos albums public. Photos on profile timeline are already protected by profile privacy, but photos on homepage timeline are better to keep public since it's public timeline.

**Comment by toxalot** [comment]
15) Except if I post a photo to my personal timeline, it will show up in Public photos block and photo albums block. Those are not protected by my profile privacy.

**Comment by andrewboon** [comment]
9) I think it is indeed an issue and we're working on an alternative implementation.
