### ISSUE TITLE
When uploading image from smartphone (iphone, samsung, nokia..) you get error "Wrong file extension"

### ISSUE THREAD

**Issue by newton27** [boonex/dolphin.pro#34]
http://www.boonex.com/forums/topic/upload-image-from-smartphone-Error-Wrong-file-.htm

Comment by Robbi:
"I noticed that phones save the file as jpeg and the extensions accepted automatically in admin panel are (jpg png gif) I did try adding jpeg but still got same error."

I tested, and is working fine using my Android device.

Further testing reveals certain devices same jpg's under different names, mainly "jpeg" with the "e" added.
Adding the "jpeg" in the photos module settings extensions area has no effect, still the same error.

**Comment by mistersenornathan** [comment]
Reproduced this, but adding 'jpeg' to the allowed extensions list did work for me.

**Comment by newton27** [comment]
I was going by what the two testers told me. I don't have a device they were talking about.
Suppose this should be closed.

**Comment by mistersenornathan** [comment]
No, I don't think this should be closed. Better would be to have 'jpeg' added to the list of allowed extensions. I can see why it was left off, I haven't seen that extension used in years.
