### ISSUE TITLE
Profile edit button should be included in actions block for admin

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#344]
The edit button only appears in profile actions block when viewed by profile owner, but not when viewed by admin.

**Comment by toxalot** [comment]
The edit link in the drop-down within blocks should also show up for admin.

And the edit drop-down should be added to the special Description block.

**Comment by moonsoon2u** [comment]
It will be a privacy breach. Admin should only touch that content which has been reported. If the profile have been reported, the member should be warn or in extreme action delete the profile. In simple words, member will think Admin stalk them and members will not trust you or your website.

**Comment by toxalot** [comment]
@moonsoon2u I disagree. Admin already has edit links for each member via the admin panel. This just makes it more accessible while browsing the site. And you can control what an admin can edit via the Profile Fields Builder.

How members view admin is a matter of how you personally manage your site and has nothing to do with what links you have available to you.
