### ISSUE TITLE
Bug with checkbox fileds in search.php member form

### ISSUE THREAD

**Issue by angelflo** [boonex/dolphin.pro#352]
In the search member form (search.php), if you use checkbox (multi selector) field, when you clic on "search" button, you loose all the selected values.

The list of members who's return is ok, you have the selected options of the checkbox well return in the url GET param but the search form don't check the url GET param values to add "checked" in the input type checkox form.

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin.pro/issues/314

**Comment by angelflo** [comment]
Hi Alex,

Thanks for your reply, but I don't understand why you close my bug on
github.

I speak about search.php (dedicated to the members search) file and the
aDefaultParams variable (I think) who do not refill the selected checkbox
previously filled correctly.

I tried to upload you serachkeyword.php file but nothing change in
search.php and I have exactly the same problem with the search memeber form
!

Regards


2016-02-29 23:14 GMT+01:00 Alex Trofimov <notifications@github.com>:

**Comment by AlexTr** [comment]
Sorry, I thought about regular search, where we've made similar fix.
