### ISSUE TITLE
Html block- Visibility option for Admins Only

### ISSUE THREAD

**Issue by moonsoon2u** [boonex/dolphin.pro#358]
Right now Html block have option to choose
 
Visible for
1.Guest   2.Member
A third option for Admins will be very helpful. This way admins can update parts of  a live website without giving a notification of "Under maintenance" . So it would look like this

Visible for 
1. Guest   2.Member  3.Admin

**Comment by AlexTr** [comment]
You can already approach the same using Page Access Control module

**Comment by moonsoon2u** [comment]
Thank you for clearing that up. Just had to uncheck the "All" from the block. Block was still visible for Admin :)
