### ISSUE TITLE
Comments on timeline need to appear as comments on content's url page.

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#37]
Comments made on timeline for content need to also appear as comments on that content's static page (url).

This is not currently so. I've had members frustratingly inquire as to why this is.
Members want their comments seen, saved and responded too, no matter where they do it.
Timeline is the focal point of what members use to post & comment. Not saving those comments to the static content page creates disjointed conversations and also reduces conversations, since one doesn't see the other.

Example: I post a video on "How To Get Money Out Of Politics." On the static content page for that video, one group of members are posting their comments. On the timeline, another group of members are posting their comments to the video. One doesn't see the other comments conversation. There are two, separate, disjointed conversations on the same subject. Illogical. Comments need to be merged.

Forum thread: http://www.boonex.com/forums/topic/Friends-Timeline-Comments-on-Content.htm

Label as: Enhancement.

**Comment by launch3** [comment]
A quick follow-up as I experiment with 7.2.1.

Let's say I add a video (or photo, sound, etc.) to the site via the "+" so it has a static url.

If I then post a comment for that video on the static url, it'll show up at the top of the Timeline as most recent (which is great!).

However, if I post that same comment for the same video on the Timeline itself (instead of at the static url), the comment will appear as part of the video's existing timeline post - but not displayed at the top of the Timeline as most recent.

So, comments made for the video on the static url are shown as most recent on the timeline (good), but comments posted to the timeline itself for that video are not shown as most recent (bad). The timeline post with recent comments is still buried in the pack (and a pain in the ass to have to find).

Related to the other issue (https://github.com/boonex/dolphin.pro/issues/38) it creates two separate conversations and confuses the **** out of members. It's confusing me to correctly describe it.

1) Please, please, please merge comments & 2) recent comments for a timeline post (video, photo, etc.) should appear at the top of the Timeline as most recent. The timeline post, when a person comments on it, should be moved to the top of the timeline as most recent.

**Comment by AlexTr** [comment]
It's already working almost like you've described. When you post comment to the blog post (or video/photo/etc) on Homepage timeline or Profile timeline - this comment is displayed on content page as well. 

But you've also get notification about this comment on the timeline as separate timeline post, this is separate Timeline entity, if you post comment to this event on timeline - it is related to this timeline event only, and can't be displayed on content page.

We'll try to discuss, what we can do about it.
