### ISSUE TITLE
Outline "likes" don't update automatically

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#372]
It seems like Ajax doesn't work for Outline "likes".
They refresh only after you reload the page.

----

Upon clicking "Like" in Outline it refreshes cound in Timeline.

**Comment by DancerDates** [comment]
It would be nice if the colour of the thumbs up like icon can be changed to blue to indicate that you liked it, and also a link added to the like count that you can click on to see who has liked the post... 

knowing that the post is liked is not enough, knowing that you liked it is important and knowing who else has too is ;)
