### ISSUE TITLE
Video Uploads stuck in Pending Processing

### ISSUE THREAD

**Issue by TexasDragon** [boonex/dolphin.pro#39]
New install on a GoDaddy shared hosting acct.  I know not the best way to go.  

I did a clean install of 7.2 mainly for the updated FFMPEG.EXE.  So I did a test video upload to 2 different albums, 2 different videos (2 different codec types (wmv, mp4)), and both are stuck in pending.  I tried forcing Cron.php, and no go.. Not even an email from the cron system.  with 7.1.6, I got an email, and it did process the videos.  Albeit, not entirely all videos, thus the reason for going to 7.2. Now it wont process any.

Bug?

Steve

**Comment by mistersenornathan** [comment]
Not a bug, likely a setup or install issue. Please open a thread for this: http://www.boonex.com/forums/

**Comment by TexasDragon** [comment]
Ok.  Just so ya know... Im not a complete duffer when it comes to installing, setting up, configuring, and using Dolphin.  But I'll play devils advocate and give you the benefit of the doubt and redo the whole darn install.  Again. This time, lets use the top listed hosting on Boonex's own site.  HostForWeb.com.  Ive used them before, and they are great.  Love Cpanel, and a whole other list of options they provide.  Again, using shared hosting, but I have a dedicated IP.  WooHoo.  But, always a but, they don't have a way to stop and restart web services, so I can use my own PHP.ini (PHP5.ini) files.  Hmm.. So I had to have them up a couple PHP memory and max settings right off the bat.  

Im on a tangent, I apologize.

To the point, Dolphin 7.2 setup again.  Test upload under the Administrator account another video.  Its a .wmv file that is 17 minutes long.  and lo and behold, it is stuck in Pending Processing.  Now, Thank you for the link to look at some "hints" as to what might be causing this, but to no avail has any of those hints actually shed any light as to the problem.

Question, now could this be a bug?

**Comment by mistersenornathan** [comment]
I'm not questioning your intelligence or anything. I've messed up installs before, and I do probably 10-20 a week. Heck, one time I downloaded a copy directly from BoonEx, and it was bad. But from what I've tested and used, video uploads work fine on 7.2, so this is more likely a setup or some other issue that needs to be troubleshooted.

But if you don't want to post to the forums, that's fine. Did you setup the cron job? If so, make sure to check the cron job notification email, and see if there are any messages about FFmpeg. If so, post them here. If a video is stuck in processing, it means the cron job is either not setup or can't process the video for some reason (e.g., it's hitting the memory_limit, or some other PHP limit).

**Comment by TexasDragon** [comment]
My sincerest apologies.  It finally worked.  No changes were made to the settings..  It just took a half hour to publish.  This has been a little frustrating.  I had hoped that I could use the latest ffmpeg in 7.1.6, but decided to go to 7.2 since it had a more recent version. So Ive been rebuilding.

I consider this case closed.  However, should it take so long?

**Comment by mistersenornathan** [comment]
This is shared? There's probably some kind of resource limiting going on, which is throttling and thus slowing down the processing. This is unavoidable, but some hosts have higher limits than others. Also, with the HTML5 module, Dolphin converts the file into additional formats, which means you need to multiply the time it takes to convert one file. If you'll be uploading a lot of videos, especially of higher file sizes, a dedicated server is better if you need them uploaded and processed quickly.

Just to be sure, I also tested a WMV and MP4 file, and both processed successfully.
