### ISSUE TITLE
Comments: Links of a certain length are incomplete or not made at all

### ISSUE THREAD

**Issue by notsenornathan** [boonex/dolphin.pro#397]
Posting a comment with a longer address causes only part of the address to be created as a link. The rest is in plaintext, or sometimes the address is entirely plaintext. For example:

* www.example.com - works
* www.example.com/example - works
* www.yourexampledomainhere­.com­ - no link is made
* www.example.com/examplelink - incomplete (www.example.com/exampleli[nk])

It also seems an address needs the www. to be added as a link. If the address is added without the subdomain, it won't work, unless it includes http:// or https:// first.

**Comment by kisonik** [comment]
The error still persists.
Try to publish this link:
http://www.pcgamer.com/th­e-best-csgo-tips-ive-rece­ived-from-angry-teammates­/­
