### ISSUE TITLE
Timeline / YouTube issue

### ISSUE THREAD

**Issue by Ilbellodelweb-Raff** [boonex/dolphin.pro#40]
If you choose to enable only the "Embed" uploader for the default module Boonex Videos, and you try to embed a youtube video from the timeline (i.e. in the homepage), you get the video informations and the thumbnail but...the button "Submit" has no effect. The video is not embedded/uploaded.

Browsing the folder "flash/modules/videos/files"

you can see here 3 files:

    1_temp.jpg
    1_temp_small.jpg
    1_temp_small_2x.jpg

The upload/embedding fails but these (temp) files are still here (folder "flash/modules/videos/files") .

There is another issue related to this problem.

Later, all the youtube uploads displays always a wrong thumb (due to the presence of the temporary files created by the failed upload)

**Comment by newton27** [comment]
Confirmed on my test site.

**Comment by yanivz** [comment]
on my site as well

**Comment by AlexTr** [comment]
http://www.boonex.com/forums/topic/Timeline-YouTube-issue.htm

**Comment by AlexTr** [comment]
Related issue:
http://www.boonex.com/forums/topic/Dolphin-7-2-Bugs.htm
point 1)
