### ISSUE TITLE
Image upload not working (wrong file extension)

### ISSUE THREAD

**Issue by ChilleX5** [boonex/dolphin.pro#401]
hello,

i have a dolphin site freshly installed but i have not been able to upload pictures on my site. im always getting this error (wrong file extension). i have included the file extensions in the photo settings but i still get this same error messgage. what is a community site if members cant share pictures. i also noticed that others people have complained about this same isssue but no solution yet. this is too bad. no help from the admins. is this how boonex treats customers?. please, you guys really need to fix this issue.

thanks.

**Comment by AlexTr** [comment]
Hello!

Please could you reproduce the issue on http://demo.boonex.com ?

**Comment by ChilleX5** [comment]
yes. i tried embedding youtube video on demo.boonex.com but it doesnt
work..."video upload fail".

**Comment by AlexTr** [comment]
Could you provide the url to youtube video which isn't working for you ?

**Comment by ChilleX5** [comment]
https://youtube.com/watch?v=DtFwwus8mkM

On Tuesday, April 26, 2016, Alex Trofimov <notifications@github.com> wrote:
> Could you provide the url to youtube video which isn't working for you ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
https://ci3.googleusercontent.com/proxy/aqL8mxYNhV8kU3tUKz37rSaC09_ISOYlVqOzJZtfXWUHQIRJMvScMuy3h_qGG8y7d7BLGe48J6igEJKgskmjGWt-NzDsfzkGzFLM3O1CLkl3ali2VaZuA6qd7LZoUk4iaazN8Jup8AYsvp_98ghxh5QsWxxFhw=s0-d-e1-ft#https://github.com/notifications/beacon/ARwO0yx7CmlCPifslK-ighxGuSu4GY4Gks5p7XEPgaJpZM4INogO.gif
>

-- 
Sent from Gmail Mobile

**Comment by AlexTr** [comment]
This is known problem, some videos aren't inserting - https://github.com/boonex/dolphin.pro/issues/377
I've added your video to the list of non-working videos in the issue.
It will be fixed in the upcoming update.

**Comment by ChilleX5** [comment]
Not just that particular video. All the different youtube videos I tried to
embed in my site failed to embed.

On Wednesday, April 27, 2016, Alex Trofimov <notifications@github.com>
wrote:
> This is known problem, some videos aren't inserting - #377
> I've added your video to the list of non-working videos in the issue.
> It will be fixed in the upcoming update.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
https://ci3.googleusercontent.com/proxy/9750H0hdo-mv--Kvugijzcj50_KjonfHHJ9BPcH973V49nqVEfQKCXyO2VDwHKAYmkhiG6Pe43CXiI3hmWR5320cF6mJLAXSRCVl4y6BSx82CWL2JJgPCTIqp7eX7kgc6Kq220vpG28crXlygzQiACsMmLcCvA=s0-d-e1-ft#https://github.com/notifications/beacon/ARwO0wRgWUM3DsVMnyLON2Ok9kYUKETTks5p7zxAgaJpZM4INogO.gif
>

-- 
Sent from Gmail Mobile

**Comment by ChilleX5** [comment]
I also discovered that the site menus (header and footer menu) are not
displaying well on mobile devices. Any help?
Thank you.
On Friday, April 29, 2016, Ochemba Chinedu <ochembachinedu@gmail.com> wrote:
> Not just that particular video. All the different youtube videos I tried
to embed in my site failed to embed.
>
> On Wednesday, April 27, 2016, Alex Trofimov <notifications@github.com>
wrote:
>> This is known problem, some videos aren't inserting - #377
>> I've added your video to the list of non-working videos in the issue.
>> It will be fixed in the upcoming update.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub<
https://ci3.googleusercontent.com/proxy/9750H0hdo-mv--Kvugijzcj50_KjonfHHJ9BPcH973V49nqVEfQKCXyO2VDwHKAYmkhiG6Pe43CXiI3hmWR5320cF6mJLAXSRCVl4y6BSx82CWL2JJgPCTIqp7eX7kgc6Kq220vpG28crXlygzQiACsMmLcCvA=s0-d-e1-ft#https://github.com/notifications/beacon/ARwO0wRgWUM3DsVMnyLON2Ok9kYUKETTks5p7zxAgaJpZM4INogO.gif
>
>
> --
> Sent from Gmail Mobile
>

-- 
Sent from Gmail Mobile

**Comment by AlexTr** [comment]
It maybe some problems with hosting or ffmpeg binary. I would suggest to ask questions in the forum:
https://www.boonex.com/forums/
