### ISSUE TITLE
Memberships: Multiple memberships and prices do not work

### ISSUE THREAD

**Issue by notsenornathan** [boonex/dolphin.pro#41]
When I create a membership level, set a price, and activate it, I see this:

<img width="810" alt="screen shot 2015-09-12 at 12 31 44 pm" src="https://cloud.githubusercontent.com/assets/14158409/9832493/42c2f2dc-594a-11e5-96f0-73bdae541c67.png">

When I add a second price to the same level (e.g., 30 days and 60 days), I see this:

<img width="810" alt="screen shot 2015-09-12 at 12 32 37 pm" src="https://cloud.githubusercontent.com/assets/14158409/9832502/69a713ce-594a-11e5-9a6d-45a77822305c.png">

When I add another membership level (both levels with only one price), I also see this:

<img width="810" alt="screen shot 2015-09-12 at 12 32 37 pm" src="https://cloud.githubusercontent.com/assets/14158409/9832502/69a713ce-594a-11e5-9a6d-45a77822305c.png">

So it seems the membership levels currently only work with one paid level and price.

Steps to reproduce:

1. Create a membership level
2. Set two prices
3. Enable it

or...

1. Create a membership level
2. Set one price
3. Enable it
4. Create another membership level
5. Set one price
6. Enable it

**Comment by AlexTr** [comment]
http://www.boonex.com/forums/topic/Membership-Payment-Help.htm
