### ISSUE TITLE
Photo Embed URL Box Missing : Timeline & Module

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#421]
In trying to embed a photo today on the timeline & from the module, I noticed that the box to paste a url is missing.

![timeline-photo-embed-v73](https://cloud.githubusercontent.com/assets/13964338/15511114/338d0fb0-21a8-11e6-8a19-909ce4c1eb96.png)

![photo-module-embed-v73](https://cloud.githubusercontent.com/assets/13964338/15517441/b5c11388-21c5-11e6-866a-01c162f2f521.png)

**Comment by AlexTr** [comment]
Can't reproduce the issue.
