### ISSUE TITLE
Migration module/script

### ISSUE THREAD

**Issue by mistersenornathan** [boonex/dolphin.pro#43]
Similar to the old 6.1 => 7.0 migration module, it would be a nice feature to be able to import data between versions. For example, if the current site is too modified or trashed to upgrade, or is too outdated. This could also be used as a base to import from other scripts.

**Comment by AlexTr** [comment]
We've made migration data when it was too many changes, now it can be upgraded. If version is too modified and only the data is important, then 3rd-party modules can be uninstalled and the whole script can be re-uploaded and upgrade script run - it should be very similar to the migration.
