### ISSUE TITLE
Shopping cart: edit the title of the cart

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#430]
The current title says, for example:
**admin's cart**
This is the same for both the **Membership** and the **Store** modules.
We could make it similar to that on BoonEx, for example:
**ADMIN SHOP**

**Comment by notsenornathan** [comment]
For membership levels, it should say <SiteName>'s Store (or Shop). Or maybe just specify it as:

Seller: <SiteName> or <SellerName>
