### ISSUE TITLE
Logo responsive issues

### ISSUE THREAD

**Issue by notsenornathan** [boonex/dolphin.pro#449]
The logo is not resized properly on smaller screens.

Here's the logo on a desktop:

<img width="363" alt="screen shot 2016-07-10 at 3 33 54 pm" src="https://cloud.githubusercontent.com/assets/14158409/16715633/cb0d45fa-46b3-11e6-86ca-8e4a36906c9d.png">

And here it is on an iPhone 6s Plus:

<img width="225" alt="screen shot 2016-07-10 at 3 34 06 pm" src="https://cloud.githubusercontent.com/assets/14158409/16715634/cb2dba38-46b3-11e6-8053-ee55ead91210.png">

This looks to be caused by the fixed height applied directly to the image in BxBaseFunctions.php:

```
function genSiteLogo()
    {
        $sLogoUrl = $this->getLogoUrl();
        if (!$sLogoUrl)
            return '<a class="mainLogoText" href="' . BX_DOL_URL_ROOT . 'index.php' . '">' . getParam('site_title') . '</a>';
        $sLogoUrl2x = $this->getLogoUrl(true);
        $sLogoW = getParam('sys_main_logo_w');
        $sLogoH = getParam('sys_main_logo_h');
        $sStyle = $sLogoW && $sLogoW ? " style=\"width:{$sLogoW}px; height:{$sLogoH}px;\" " : '';
        $sLogoAttr2x = $sLogoUrl2x ? " src-2x=\"$sLogoUrl2x\" " : '';
        $sClass = 'mainLogo' . ($sLogoAttr2x ? ' bx-img-retina' : '');
        
        return '<a href="' . BX_DOL_URL_ROOT . '"><img ' . $sStyle . ' src="' . $sLogoUrl . '" ' . $sLogoAttr2x . ' class="' . $sClass . '" alt="' . bx_html_attribute(getParam('site_title')) . '" /></a>';
    }
```

**Comment by AlexTr** [comment]
Can't reproduce the issue, please specify how to reproduce it ?

**Comment by notsenornathan** [comment]
Sample image:

![sys-v4-logo-2x](https://cloud.githubusercontent.com/assets/14158409/16754383/39c4445a-47c0-11e6-8fd1-919ddea8d7cb.png)

The trick is to have the image large enough that it's impacted by the boundary of the header - so it's resized.
