### ISSUE TITLE
Is dolphin.pro free to use?

### ISSUE THREAD

**Issue by duruitang** [boonex/dolphin.pro#452]
I want to download and install it on my own server.

**Comment by notsenornathan** [comment]
Please note that GitHub is only for feature requests and issues. For general questions and support, please use BoonEx.com.

Dolphin is free to use without any time limits. It does require a license, or else it will run in free trial mode; there's no time limits, and all the bundled modules are still included and can be installed and used. In free trial mode, a Powered by Dolphin banner shows and the separate Android and iOS apps can't be used. A license removes these two restrictions, and one can be added at any time.
