### ISSUE TITLE
Groups: View Fans problem

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#467]
When creating or editing a Group, if you choose "Fans Only" for the "View Fans" privacy setting, this value does get saved in the database and gets replaced with "Me Only".

**Comment by AlexTr** [comment]
@kisonik can't reproduce on demo.boonex.com

**Comment by AlexTr** [comment]
возможно проблема с апгрейдом, так как я проверял на проапгреденном сайте, а не на чистой инсталляции.
