### ISSUE TITLE
Profile Image/Photo Too Complicated

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#492]
Please make uploading or changing a user's profile photo easier than it is. Way too complicated. Getting a number of emails from frustrated members. Users should be able to click on a little icon layered above the photo. Just like "change cover" photo.
See Facebook.
Or ilbellodelweb's Mega Profile.
Both make it super simple.

**Comment by autoktone** [comment]
Hello,
thanks for the idea, here how I did but this modifies the core files... it should be done in your template directory.

In \templates\base\profile_cover.html, after "div class='sys-profile-cover-actions bx-def-padding'" add
`			<a  class="bx-btn bx-btn-small sys-pca-change-background" href="__thumbnail_href__">
				<i class="sys-icon user sys-pca-icon"></i>
				<span class="sys-pca-text" ><bx_text:_sys_btn_avatar_change /></span>
			</a>`

In \templates\base\scripts\BxBaseProfileView.php, modify the bolded lines
    function showBlockCover( $sCaption, $bNoDB = false )
......
		$sContent = $GLOBALS['oSysTemplate']->parseHtmlByName('profile_cover.html', array(
			'background_class' => $sBackgroundClass,
			'bx_if:show_background' => array(
				'condition' => !empty($sBackground),
				'content' => array(
					'background' => $sBackground
				)
			),
			'bx_if:show_actions' => array(
				'condition' => $bProfileOwner && BxDolRequest::serviceExists('photos', 'get_album_uploader_url'),
				'content' => array(
					**'href_upload' => BxDolService::call('photos', 'get_album_uploader_url', array($p_arr['ID'], 'profile_cover_album_name')),
					'thumbnail_href' => $sProfileThumbnailHref,**
				)
			),

**Comment by launch3** [comment]
This mod by autoktone both works and is definitely an improvement.
