### ISSUE TITLE
Guest Commenting Bug On Timeline/Wall

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#501]
When a guest comments on a site, audio, video, etc., the comment is attributed properly in the comments section on that respective page. OK.

However, when these same guest comments are added to the wall/timeline, either no attribution is included (if not logged in) or admin is attributed (if logged in).

Examples below...

![timeline-wall-guest-attribution](https://cloud.githubusercontent.com/assets/13964338/20322105/c87a2e88-ab45-11e6-8a3d-f0e32ba295ce.jpg)

**Comment by AntonLV** [comment]
Need to check related issue https://www.boonex.com/forums/topic/Error-in-timeline.htm

**Comment by AntonLV** [comment]
The issue was already fixed in Ticket #418
