### ISSUE TITLE
Photo Upload enhancement

### ISSUE THREAD

**Issue by robbie778** [boonex/dolphin.pro#517]
This is not a bug but would be an excellent enhancement if ever worked on. A Cloud or Amazon S3 upload option. Where all photo uploads go directly to either google cloud or amazon s3 bucket. Photo's are viewable still after upload.

Many people on github have amazon s3 api's already built for php. It be great if we could have an option in admin panel under photo module to activate S3 uploads. If I ever had the time to understand this scripts code i would of done it myself and made a fortune from a mod.

It would massively increase popularity of dolphin because it means less server power is used and more users can sign up without memory running out on server. It has been requested for last 3 yrs but no one ever listened. I hope some genius can make it happen in 7.3.4!

:D

**Comment by AlexTr** [comment]
There is S3 storage support in UNA (which is actually future version of Dolphin):

https://una.io
