### ISSUE TITLE
Class Thing not found in BxOAuthAPI.php

### ISSUE THREAD

**Issue by sduensin** [boonex/dolphin.pro#519]
OAuth2 to Chat+ isn't working.  Stubbing in "Thing" fixes it.  I was unable to get bx_include('Thing') to work.

**Comment by AlexTr** [comment]
Is it happening in Dolphin 7.3.3 or in current version downloaded from GitHub ?

**Comment by sduensin** [comment]
Master from GitHub.

**Comment by AlexTr** [comment]
Thank you for the report.
