### ISSUE TITLE
site thumbnails in outline

### ISSUE THREAD

**Issue by yanivz** [boonex/dolphin.pro#523]
The site thumbnail in outline is very small from other thumbnails eg. photos.

In the site module setting image size is set to xlg.

I saw in the HTML with firebug that the thumbnail original size is 324X240 but the system resize it to 140X105

https://www.boonex.com/forums/topic/site-thumbnails-in-outline.htm

p.s

even when upload image manually it keep its small proportion 

![download](https://cloud.githubusercontent.com/assets/4169780/22221811/271d9544-e1bd-11e6-8c70-637cbea96b98.png)

**Comment by AlexTr** [comment]
I've uploaded custom image and it's not displaying:
![screen shot 2017-09-27 at 8 02 53 pm](https://user-images.githubusercontent.com/3324866/30917953-fbdaef7a-a3be-11e7-8e11-7da818d8f58f.png)

When opening this image in new window:
![screen shot 2017-09-27 at 8 03 03 pm](https://user-images.githubusercontent.com/3324866/30917972-0a2543d2-a3bf-11e7-8061-eb7fedfe3eeb.png)

**Comment by AntonLV** [comment]
Yes, you are right. The issue appeared because of the fix from Ticket #582. 
I've updated the fix.
