### ISSUE TITLE
iOS: current location isn't detecting in iOS 10.2.1

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#529]
https://www.boonex.com/forums/topic/location-search-in-Dolphin-app-on-iOS-10-2-1-.htm
https://www.boonex.com/forums/topic/Location-search-on-Dolphin-App-no-result.htm
https://www.boonex.com/forums/topic/Near-Me-isn-t-working-in-mobile-app-.htm

**Comment by josh415** [comment]
Do we have any updates on this?

**Comment by AlexTr** [comment]
@josh415 not yet, we'll fix with the upcoming update

**Comment by josh415** [comment]
Thanks for letting me know. Do we have an ETA for that? It sort of renders my iOS app useless

**Comment by AlexTr** [comment]
I hope we'll work on new version in 1-2 month, but it's very rough.

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin-ios/commit/3cb6f1efe60ae186bbe75929f3684e350c837e03
