### ISSUE TITLE
Videos View - Related Video Block does not appear

### ISSUE THREAD

**Issue by asifmars** [boonex/dolphin.pro#530]
On Videos View page Related Video block is not appearing even after adding related keyword.

**Comment by AntonLV** [comment]
The issue cannot be reproduced on [demo.boonex.com](http://demo.boonex.com)
1. The block is disabled by default. You  may activate it via admin panel -> Pages Builder.
2. If 'full-text search' is disabled in admin panel -> advanced settings (this is so by default) then Title and Tags are used for searching. So, if you have similar titles and tags, Related Video block will be shown.
