### ISSUE TITLE
Facebook share in EVO template

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#534]
After sharing blank screen is shown with the following URL:
`https://www.facebook.com/dialog/return/close?#_=_`

https://www.boonex.com/forums/topic/Facebook-sharer.htm

**Comment by anzacks** [comment]
Alex, while waiting for permanent solution, can u modify the code so that when the share butt9n clicked it open to new blank window?

**Comment by AlexTr** [comment]
@anzacks you can apply the fix from the above commit
