### ISSUE TITLE
Google Recaptcha 2.0

### ISSUE THREAD

**Issue by Elshara** [boonex/dolphin.pro#551]
Support for the 2.0 api does not yet exist in dolphin. I think members should have the option of switching between 1.0 and 2.0 and perhaps have a sign up quiz you could set up, to give people better spam control. Rather than just having one option for people to be required to fill out.

**Comment by flth** [comment]
Why v1 needs to be supported anymore at all? It's deprecated by Google for almost a year now.

**Comment by Elshara** [comment]
I'm surprised they still have it up. When they disabled their old
youtube api, they sure never kept it going.

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin.pro/issues/59
