### ISSUE TITLE
Profile Pruning: Base "last login" date on user's registration date if they haven't logged in

### ISSUE THREAD

**Issue by tchbnl** [boonex/dolphin.pro#558]
Right now pruning will delete an account if the user hasn't logged in once, because the default is to set the last login value to 00-00-0000 or similar. To work around this, it may be better to have pruning use the user's registration date in case the last login date isn't available. That way the user will have more time to login, and such inactive accounts will still be deleted based on the registration date.

**Comment by Elshara** [comment]
Or, another way for accounts to not be considered for account deactivation by pruning, is if the person has made x amount of posts and or specific post types. Such accounts could be then moved to a user group pending pruning activities. This way you have better control over the action.
