### ISSUE TITLE
Facebook Connect - Auto Friend

### ISSUE THREAD

**Issue by OdinWynd** [boonex/dolphin.pro#563]
Facebook Connect works to log-in in 7.3.3 but the auto add friend feature is not functioning properly..

**Comment by OdinWynd** [comment]
UPDATE:  After further digging, it seems Dolphin 7.3.3 is using Graph API 1.0 to grab a friends list.. Or, there is a bug.

There are 2 issues, one, Graph API 1.0 is retired and unavailable on apps made after April 30, 2014.

2nd, if the user app was made before April 30, 2014 Facebook Connect is only calling the first 50 friends instead of the friends list... changing 
$oFriendsResponse = $this -> oFacebook -> get('/me/friends?limit=50'); on line 300 to $oFriendsResponse = $this -> oFacebook -> get('/me/friends?limit=5000'); will grab the entire friends list..

But, this only works for people who have installed and connected Facebook Connect to their Facebook developer account before April 30, 2014

Graph API 2.0 only allows to grab data from friends who use the app as well, or returns empty on those calls... 

Even though I have friends using the app, it is giving empty returns on calls through Dolphin...

Also, if the bug was not present, you would still be limited to only the first 50 friends using this app... 5000 is the magic number, that is the friend limit for a Facebook account.

If I find further information, like a setting that must be enabled now on the Facebook side of things, or if I find the bug, I will update this again.

**Comment by OdinWynd** [comment]
Current Graph API is 2.8 ... Dolphin is sending 2.4 calls.... 2.4 calls are automatically updated and returned as 2.8 gets... I tested the api call on the Facebook side and it works like a charm... But it is not working in Dolphin 7.3.3 ... Trying to isolate why

**Comment by Valentinez** [comment]
Mine seems to not be collecting any information, aside from first name, and e-mail.
When I check get extended profile info, I got an error, it seems 'bio' is deprecated, they use 'about' now.

However, after I altered the code, it wasn't grabbing anything, Full Name, Gender, Birthday, and Description are all blank, but I get no errors...
