### ISSUE TITLE
EVO Jumpy Background in IE

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#572]
change this one line of CSS in the general.css file for `div.sys_root_bg` to stop the background from jumping around when scrolling in IE Browser.   
FIND:   
```css
background-repeat: repeat;
``` 
REPLACE WITH:   
```css
background-repeat: repeat center center fixed;
```

**Comment by AntonLV** [comment]
I did the changes but I cannot reproduce the "Jumpy Background" issue in IE 10 and any emulation modes (IE9, IE8, IE7) in it.
