### ISSUE TITLE
Facebook removed FacebookLocales.xml file

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#576]
The following URL stop working:
https://www.facebook.com/translations/FacebookLocales.xml

So use local file instead of this URL:
https://www.boonex.com/forums/topic/Out-of-no-where-500-Error-on-content-load-.htm#283071

**Comment by gijo-varghese** [comment]
The issue is still there

**Comment by AlexTr** [comment]
@gijo-varghese Please apply the following fix:
https://www.boonex.com/forums/topic/FacebookLocales-xml.htm
