### ISSUE TITLE
Photos(all media modules): privacy should be checked when file is access by direct image URL

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#582]
https://www.boonex.com/forums/topic/Security-and-permissions-of-the-photo.htm

**Comment by AntonLV** [comment]
Files, Sounds and Videos already have similar checking.

**Comment by AlexTr** [comment]
I suspect that this problem occurs because of this modification:
https://github.com/boonex/dolphin.pro/issues/523#issuecomment-332531788

**Comment by AlexTr** [comment]
There are broken images displayed when user can't view images:
![screen shot 2017-10-04 at 4 46 42 pm](https://user-images.githubusercontent.com/3324866/31172022-c21bde42-a923-11e7-9385-c0d57f9e55e6.png)

I think we need to display some predefined image when there is no access, instead of HTML page
