### ISSUE TITLE
Dolphin Pro is not working with PHP 7 ?

### ISSUE THREAD

**Issue by elaur** [boonex/dolphin.pro#588]
Dolphin Pro is not working with PHP 7 ?

**Comment by AlexTr** [comment]
There is new branch which is still in development which is compatible with PHP 7, if you to try it (don't use for production, use only for testing purposes) you can download it here:
https://github.com/boonex/dolphin.pro/archive/master.zip

**Comment by elaur** [comment]
Is possible to know if there is any ETA for the next version with php 7 support?

**Comment by AlexTr** [comment]
No ETA for Dolphin 10 yet, but we have [UNA](https://una.io), which as actually future version of Dolphin which got new name because of many changes and radical facelift
