### ISSUE TITLE
Upgrade to reCaptcha v2

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#59]
​http://www.boonex.com/forums/topic/reCAPTCHA-v2-.htm
https://www.boonex.com/forums/topic/Query-regarding-roadmap-for-reCAPTCHA-V2.htm

**Comment by AlexTr** [comment]
make sure it is responsive

**Comment by apachler** [comment]
Oh wow guys, Google told me that they disable the V1 API on 2018-03-31. So we are in a hurry. Please add support for V2. Thanks!
