### ISSUE TITLE
Newline escape sequence char (\n) showing in Tooltips

### ISSUE THREAD

**Issue by robATgit** [boonex/dolphin.pro#601]
The newline escape sequence char (\n) is showing in Tooltips.
This happens when you use ENTER to force a newline while editing the Description of a field.
I looked in the mysqlDB and noticed the \n are also in other texts as default.
This means that either my system (linux) is interpreting them incorrectly or the Dolphin system is.

Thanks
Robert

**Comment by AlexTr** [comment]
Could you please describe in details where exactly it can be reproduced?

**Comment by robATgit** [comment]
Hi Alex.

In Fields Builder.

If I write this into " Field Description", or paste in into "Field Description" from a plain text editor

Big   Business. > $999/ Month.
Small Business. > $99 / Month.
Personal. No minimum.

I get this in the tooltip when hovered over.

Big   Business. > $999/ Month.\nSmall Business. > $99 / Month.\nPersonal. No minimum.

So somewhere its interpreting \n as chars not newlines.

Here are 2 small screen shots.

![image](https://user-images.githubusercontent.com/32213674/31160355-21d3e80e-a913-11e7-80ad-b6f6b17e49fb.png)

![image](https://user-images.githubusercontent.com/32213674/31160435-b1cfc73e-a913-11e7-8505-332732b01ce2.png)

Thanks
Robert
