### ISSUE TITLE
Payment: Manual order for membership does not reset actions limits

### ISSUE THREAD

**Issue by tchbnl** [boonex/dolphin.pro#621]
If a manual order is done in the Payment module, the sys_acl_actions_track table isn't cleared for the user when their level is changed - so their old limits still stand.

**Comment by AntonLV** [comment]
It doesn't matter how the payment was processed (common purchase or manual order) in Payments module. All of them use the same mechanism to let Membership module know that it should process purchased membership level. More over exactly the same function setMembership (from membership_levels.inc.php file) is used to update membership level here and in Admin panel. 
When membeship level is purchased or processed manually and a client already has non-Standard membership level then this new level is set in the queue and will start after the old one expires. In this case sys_acl_actions_track isn't cleared for the client during purchase or manual order processing. 
It's cleared if you (as admin) are setting a membership level via Dolphin admin panel -> Members section and check 'Starts immediately' checkbox, which means that the script should ignore an old membership level and use new one immediately.
