### ISSUE TITLE
Fix appearance of "Share" button in browse.php page

### ISSUE THREAD

**Issue by LeonidSokushev** [boonex/dolphin.pro#628]
From this request https://www.boonex.com/forums/topic/Share-Button-on-Evo-Template-when-Logged-Out.htm see cases when this button isn't available.

But it should be there constantly as feature of "EVO" template.

**Comment by AlexTr** [comment]
This button is exclusively for EVO template. However it looks like a bug that it's not shown when user is logged-in.
