### ISSUE TITLE
Facebook Connect issue: no profile info

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#63]
When creating an account through Facebook Connect, no email, no username, and no additional profile info is collected.
Although, the profile avatar is fetched properly.

**Comment by AlexTr** [comment]
Can't reproduce.

**Comment by Ilbellodelweb-Raff** [comment]
I’ve got the the approval for the extended info of Facebook as you can see in the attachment, and I’ve turned “on” the "Fetch Extended Profile Info" option in Dolphin "Facebook Connect" module.
    But logging with Facebook the result is always the same: no info about the birthday, about the first name, the last name (only the fullname, the email, the picture and the sex are fetched). In other words only the default profile informations (and also for the name, only the full name is got, not the first and the last name)
![fb extended info](https://cloud.githubusercontent.com/assets/14245999/18614160/d354cc12-7d89-11e6-9959-25fd56b49557.jpg)
