### ISSUE TITLE
Avatar and Profile Photo in 7.2

### ISSUE THREAD

**Issue by apachler** [boonex/dolphin.pro#64]
Found some glitches in avatar and profile photo function, see attachments ...

1. Avatar.jpg - The preview is not correct to the selection but the cropped image is correct to the selection
2. Manage_photos.jpg - Dropdown selection out of box
3. Profile_photo.jpg - They dont use the same link, the link should point to a page where we can select what profile photo we want to use
![avatar](https://cloud.githubusercontent.com/assets/3908272/10016996/43589e02-612b-11e5-81a0-569ad97afb30.jpg)
![manage_photos](https://cloud.githubusercontent.com/assets/3908272/10016995/43561358-612b-11e5-9a15-aa6fb446358c.jpg)
![profile_photo](https://cloud.githubusercontent.com/assets/3908272/10016997/435f8776-612b-11e5-8a41-af40d6b79ca4.jpg)

**Comment by AlexTr** [comment]
Thank you for the contribution, but this is not a fix for the problems in this ticket.
