### ISSUE TITLE
7.3.5 - When viewing photos header blocking images and controls

### ISSUE THREAD

**Issue by virtualsilver** [boonex/dolphin.pro#646]
Bayvillecompass.com - 7.3.5 - When viewing photos header blocking images and controls. Occurring when viewing an album, using arrows to advance through photos page constantly jumps up and photo and controls are hidden by header forcing you to scroll down to view.
![2018-05-17_5-34-33](https://user-images.githubusercontent.com/22315453/40169851-ee9e2bb0-5994-11e8-8e65-21d3b55291c4.png)

Hidden
![2018-05-17_5-35-39](https://user-images.githubusercontent.com/22315453/40169859-f592e0a0-5994-11e8-9c01-ad276074d229.png)

**Comment by AntonLV** [comment]
The issue was reproduced in Chrome and fixed.
