### ISSUE TITLE
Developing on master

### ISSUE THREAD

**Issue by apachler** [boonex/dolphin.pro#662]
Hello there,

it seems you develop on the master branch which is at Dolphin Version 7.3.0. Would be better to use the 7.3 branch since it is at Dolphin version 7.3.5, or did i get something wrong?

Best regards

**Comment by AlexTr** [comment]
Actually master branch is 7.4, I will update version shortly

**Comment by apachler** [comment]
But you started to develop 7.4.0 on the 7.3.0 state so you missed all the changes from 7.3.1 to 7.3.5, right?

**Comment by AlexTr** [comment]
@apachler we've already merged all changes
