### ISSUE TITLE
Index page timeline privacy settings problem

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#68]
The Index page timeline privacy settings don't reflect the Profile page timeline privacy settings.
If you hide your timeline from others (make it Me Only), your posts will still be visible on the Index page timeline.

**Comment by AlexTr** [comment]
Timeline privacy inherits profile privacy, so if you hide your profile - then profile timeline will be hidden too. If you set privacy for Timeline profile block only - then it will work for this block only, not any other blocks.
