### ISSUE TITLE
7.4.1 will not accept License

### ISSUE THREAD

**Issue by manking109** [boonex/dolphin.pro#685]
mankingADVANCED11 posts0I walked through updating a 7.3.5 to 7.4.0 
It stripped out my license.I then was told to apply patch 7.4.1 

I did that license still would not apply. In frustration, I started over and installed 7.4.1 fresh install and yet still can not apply the license. 

Without the license, mobile apps will not work.

allow_url_fopen is on

Not sure how to test this..

Direct connection to boonex.com should be able to be established (i.e. connection without requiring proxy authorization). This is required for license verification.

or if there is a setting I missed PHP?? Dolpin Admin??

**Comment by AlexTr** [comment]
7.4.1 should definitely accept the license if the license is correct and isn't expired, you can reset the license for sure just in case.
Regarding mobile apps - there is different problem - https://github.com/boonex/dolphin.pro/issues/686
