### ISSUE TITLE
Upgrade script need to check permissions.

### ISSUE THREAD

**Issue by newton27** [boonex/dolphin.pro#69]
Please see this topic for how this was found.

http://www.boonex.com/forums/topic/Changes-to-header-inc-file-during-upgrade-error.htm

Basically if the upgrade is done and the /inc folder is set to non-writable the the new files like in my case "version.inc.php" does not get uploaded.

**Comment by AlexTr** [comment]
When you copy over the files and if some file/folder isn't writable - you've already get some type of error.

**Comment by newton27** [comment]
Did this get fixed?
https://www.boonex.com/forums/topic/Messed-up-while-updating-from-7-1-6-to-7-2.htm

**Comment by AlexTr** [comment]
There is nothing to fix. 
I've replied in this thread:
https://www.boonex.com/forums/topic/Messed-up-while-updating-from-7-1-6-to-7-2.htm#266101

**Comment by newton27** [comment]
What about my case, or others that have the /inc set to 555. It affected me and has others. Why don't the switch or upgrade check that folder permission?

**Comment by AlexTr** [comment]
If you have incorrect permission, then you will fail when you copy over the files. So you should get some error from FTP client or in SSH command line.
