### ISSUE TITLE
Preferred language selector at Join Form and by location.

### ISSUE THREAD

**Issue by andrewboon** [boonex/dolphin.pro#7]
Offer a choice of language on sign up, and add an option for admin to "enable automatic language setting by user location".

**Comment by AlexTr** [comment]
Language is already automatically detected by the browser's language - I believe this is correct way of auto-detecting the language. If member changes site language it is remembered for logged in users. 

So it is already auto-detected and remembered for logged-in user and there is a way to change it as well. For guests it is also remembered but in the cookies.
