### ISSUE TITLE
Join: TOS checkbox breaks responsiveness

### ISSUE THREAD

**Issue by notsenornathan** [boonex/dolphin.pro#73]
The TOS checkbox's text (well, all form text) is set to no-wrap, which ends up breaking the responsiveness of the join form - the CAPTCHA block and other blocks now try and extend past the width of the page block and get cut-off.

Steps to reproduce:

1. Add the TOS field to the join form and on the same page as the CAPTCHA
2. View join.php in a smaller window or on a phone
3. That's it

If it seems to work fine, try extending the label text a little bit.

**Comment by AlexTr** [comment]
Related issue:
http://www.boonex.com/forums/topic/7-2-text-length-problem-in-tinymce.htm#265260

**Comment by AlexTr** [comment]
There is still problem with multiple selector field:
https://www.boonex.com/forums/topic/The-text-goes-off-the-block.htm#266206

**Comment by AntonLV** [comment]
Cannot reproduce the issue with TOS. Looks like it was already fixed.

**Comment by AntonLV** [comment]
The issue
"Related issue: http://www.boonex.com/forums/topic/7-2-text-length-problem-in-tinymce.htm#265260"
cannot be reproduced too.

**Comment by AntonLV** [comment]
The issue
"There is still problem with multiple selector field: https://www.boonex.com/forums/topic/The-text-goes-off-the-block.htm#266206"
was fixed.
