### ISSUE TITLE
Bring back First name / + Last name

### ISSUE THREAD

**Issue by philverheij** [boonex/dolphin.pro#83]
Is it just me or am I missing the First name and Last name fields? We run a dating site and for "anonymity" / "privacy" members like it that it shows their First name instead of their Full name / username...

**Comment by AlexTr** [comment]
You are welcome to add any fields in profiles fields builder.

**Comment by philverheij** [comment]
We did that. Only problem is that everywhere appears the username or full name of the member because of the fact that first name isn't a option at "Member display-name" in settings.
