### ISSUE TITLE
No function to get members Full name.

### ISSUE THREAD

**Issue by deano92964** [boonex/dolphin.pro#84]
I was going to submit another pull request to add this function to inc/profiles.inc.php

function getFullName( $ID = '' )
{
    if ( !$ID && !empty($_COOKIE['memberID']) )
        $ID = (int)$_COOKIE['memberID'];

    if ( !$ID )
        return '';

    $aProfile = getProfileInfo($ID);
    if (!$aProfile)
        return false;

    return $aProfile['FullName'];
}

You seem to have added a FullName field to dolphin 7.2 and removed the FirstName and LastName fields from the Profile Table. This function is to pull the value of that new FullName field.

The getNickName function no longer seems to work. Apparently have not been updated to deal with those profile table changes.

Also Facebook connect is still trying to populate the FirstName and LastName fields even tho they no longer exist, and is not populating the FullName field.

Not sure what the hold up is on merging pull requests, but i won't be helping much if you don't have time to look at the pull requests.

**Comment by philverheij** [comment]
I also made a request to bring back the first and last name fields and let site owners choose what they want. Instead of pushing them to full name or username. We have a dating site, so we like to use First name because of the privacy / anonymity from members. And because of the personal approach we don't like to use the username in communication towards the members.

**Comment by AlexTr** [comment]
Thank you for your contribution, we'll review it shortly.
Facebook mod has been already updated to populate the proper field.
We unified to get user title (it maybe username, fullname, etc), so the function getNickName returns different info depending on admin settings:
Admin panel > Settings > Advanced Settings > Profiles > Member Display-Name
