### ISSUE TITLE
Inactive blocks in the Builders should be sorted alphabetically by Name

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#87]
Inactive blocks in the Builders should be sorted alphabetically by Name

**Comment by kisonik** [comment]
"All Items" in the Builders should be sorted automatically by name:
Navigation Menu
Service Menu
Bottom Menu
Member Menu
Admin Menu
Profile Fields

Drop-down list items should be sorted alphabetically:
Predefined Values
Pages Builder

**Comment by AntonLV** [comment]
"Drop-down list items should be sorted alphabetically" already done in Ticket #118.
