### ISSUE TITLE
PayPal improvements 

### ISSUE THREAD

**Issue by andrewboon** [boonex/dolphin.pro#91]
Feedback:

I have big difficulty with paypal flow being easy for my members that want to sell downloads. After someone purchases something from them... they have to manually process the item and then the customer has to go back to the product page before the download button shows up. I wish it would automagically take the customer back to a download button. And the seller wouldnt have to manually key in a transaction number... thank you so very much!!!

**Comment by AntonLV** [comment]
By default the paymen should be processed automatically. I think the problem appears if a seller didn't configure correctly his PayPal account and Dolphin's Payment settings in My Account -> Payments -> Settings tab.
