### ISSUE TITLE
The class BxBaseProfileGenerator isn't inherited

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#94]
The class BxBaseProfileGenerator isn't inherited.
It is located in the same file as the class BxBaseProfileView but if you inherit it in the file BxTemplProfileView, the inheritance is overridden.

https://www.boonex.com/forums/topic/Not-a-bug-but.htm

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin.pro/issues/508
